name: Build and Push to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up QEMU (für Cross-Arch Builds)
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx (für Multi-Arch Builds)
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push App Image (Multi-Arch)
      uses: docker/build-push-action@v5
      with:
        context: ./app
        push: true
        tags: ghcr.io/babsyit/mvs-app:latest
        platforms: linux/amd64,linux/arm64

    - name: Build and Push DB Image (Multi-Arch)
      uses: docker/build-push-action@v5
      with:
        context: ./db
        push: true
        tags: ghcr.io/babsyit/mvs-db:latest
        platforms: linux/amd64,linux/arm64
